a=input ("Name:")
b=input ("Age:")
c=input ("College Name:")
a=str (a)
b=int (b)
c=str (c)
print("my name is %s my age is %s my college name is %s" %(a,b,c))
Math=input ("marks of maths:")
Science=input ("marks of science:")
Nepali=input ("marks of nepali:")
English=input ("marks of english:")
Social=input ("marks of social:")
Math=float(Math)
Science=float(Science)
Nepali=float(Nepali)
English=float(English)
Social=float(Social)
sum=Math+Science+Nepali+English+Social
print("The sum of your marks is: %2f" %(sum))